# Generated by Django 4.1.4 on 2023-04-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countriesName', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
